@startuml
'https://plantuml.com/class-diagram

class 商家{
}

class 新店铺申请 {
+申请时间:date
}

class 店铺信息管理 {
}

'class 店铺信息 {
'+店铺名称:string
'+店铺地址:string
'+店铺介绍:string
'+联系方式:string
'}

class 食品管理 {
+食品名称:string
}

class 用户订单处理 {
+下单日期:string
+订单总价:double
+送货地址:string
}

class 店铺营业情况查看 {
}

新店铺申请 "0..*" -- "1" 商家
店铺信息管理 "0..*" -- "1" 商家

店铺信息管理"0..*" -up- "1" 店铺信息
店铺信息 "1" - "0..*" 新店铺申请

商家 "1" -- "0..*" 食品管理
商家 "1" -- "0..*" 用户订单处理
商家 "1" -- "0..*" 店铺营业情况查看

用户订单处理 "0..*" -- "1" 订单状态
店铺营业情况查看 "0..*" -- "1" 店铺营业信息
食品管理 "0..*" -- "0..*" 食品信息

@enduml