@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> 登录页面
state c <<choice>>
state c1 <<choice>>
state c2 <<choice>>
登录页面 --> c :是否注册账号
c --> 注册页面 :no
注册页面 --> c2 :输入注册信息
c2 --> 登录页面 :注册成功
c2 --> 注册页面 :注册失败
c --> 登录验证 :yes
登录验证 --> c1
c1 --> 商家首页 :验证成功
c1 --> 登录页面 :验证失败

商家首页 --> 申请新店铺
商家首页 --> 店铺列表页面
店铺列表页面 --> 店铺页面 :选择店铺

店铺页面 --> 管理店铺信息
管理店铺信息 --> 显示店铺信息
管理店铺信息 --> 修改店铺信息

店铺页面 --> 管理店铺食品
管理店铺食品 ---> 修改食品信息
管理店铺食品 ---> 新增食品
管理店铺食品 ---> 删除食品

店铺页面 --> 处理用户订单
处理用户订单 --> 发布派送订单
处理用户订单 --> 接收用户订单

店铺页面 --> 查看店铺营业情况
查看店铺营业情况 ---> 查看食品销售额
查看店铺营业情况 ---> 查看总营业额
查看店铺营业情况 ---> 查看当月营业额
查看店铺营业情况 ---> 查看历史营业额

@enduml