@startuml
'https://plantuml.com/use-case-diagram

left to right direction
:商家: as business

rectangle 商家子模块 {
(1.注册) as (注册)
(2.登录) as (登录)
(3.申请新店铺) as (申请新店铺)


(5.管理店铺信息) as (管理店铺信息)
(5.2修改店铺信息) as (修改店铺信息)
(5.1查看店铺信息) as (查看店铺信息)

(6.管理店铺食品) as (管理店铺食品)
(6.3删除食品) as (删除食品)
(6.2新增食品) as (新增食品)
(6.1修改食品信息) as (修改食品信息)

(7.处理用户订单) as (接单)
(7.2发布派送订单) as (发布派送订单)
(7.1接收用户订单) as (接收用户订单)

(8.查看店铺营业情况) as (查看店铺营业情况)
(8.1查看总营业额) as (查看总营业额)
(8.4查看历史营业额) as (查看历史营业额)
(8.3查看当月营业额) as (查看当月营业额)
(8.2查看食品销售额列表) as (查看食品销售额列表)

(4.选择店铺) as (选择店铺)
}

business -- (注册)
business -- (登录)
business -- (申请新店铺)
business -- (管理店铺信息)
business -- (管理店铺食品)
business -- (接单)
business -- (查看店铺营业情况)

(管理店铺信息) ...> (选择店铺) :include
(管理店铺信息) ..> (查看店铺信息) :include
(管理店铺信息) ..> (修改店铺信息) :include

(管理店铺食品) ...> (选择店铺) :include
(管理店铺食品) ..> (新增食品) :include
(管理店铺食品) ..> (删除食品) :include
(管理店铺食品) ..> (修改食品信息) :include

(接单) ...> (选择店铺) :include
(接单) ..> (接收用户订单) :include
(接单) ..> (发布派送订单) :include

(查看店铺营业情况) ...> (选择店铺) :include
(查看店铺营业情况) .> (查看总营业额) :include
(查看店铺营业情况) ..> (查看历史营业额) :include
(查看店铺营业情况) ..> (查看当月营业额) :include
(查看店铺营业情况) ..> (查看食品销售额列表) :include

@enduml