@startuml
'https://plantuml.com/class-diagram

class 线上点餐 {
==
选择商家()
选择食品()
选择地址()
生成订单()
支付订单()
}

class 订单管理 {
订单编号
==
查看订单明细()
支付订单()
}

class 地址管理 {
地址编号
==
选择地址()
新增地址()
删除地址()
编辑地址()
}

'线上点餐 "0..*" -- "1" 客户
客户 "1" -- "0..*" 线上点餐
客户 "1" -- "0..*" 订单管理
订单管理 "0..*" -- "1" 订单状态
note left of 订单状态
订单未支付，订单已支付.
end note

客户 "1" -- "0..*" 地址管理

@enduml