@startuml
'https://plantuml.com/use-case-diagram
left to right direction

rectangle 外卖平台模块{

usecase 1.分配订单

(1.分配订单) ..> (1.1创建送货订单):include
usecase 2.查询订单

(2.查询订单)..>(2.1使用订单id查询订单):include
(2.查询订单)..>(2.2查询所有未分配订单):include
(2.查询订单)..>(2.3查询所有送货订单):include




(3.管理店铺申请) ..>(3.2查看店铺申请):include
(3.管理店铺申请) ..>(3.1将店铺上架展示界面):include
(3.2查看店铺申请) ..>(3.2.1审核店铺申请):include

}

外卖平台管理员 -- (2.查询订单)
外卖平台管理员 -- (1.分配订单)
外卖平台管理员 -- (3.管理店铺申请)

@enduml