@startuml
'https://plantuml.com/sequence-diagram

autonumber
title 骑手查询未完成订单并取餐，送达

actor 用户
activate 用户
participant FrontEnd order 2
participant BackEnd order 3
activate BackEnd
database 数据库 order 6

activate 数据库
|||
用户 -> FrontEnd:登陆网站,点击未完成订单
activate FrontEnd
FrontEnd->BackEnd:传递用户id，查询该用户所有订单状态非已送达的订单
BackEnd->数据库:使用用户id查询所有订单状态非已送达的订单
数据库 -> BackEnd:返回查询结果
BackEnd->FrontEnd:返回所有未完成订单列表
FrontEnd ->用户:显示所有未完成订单
用户 ->FrontEnd:点击具体订单明细
FrontEnd ->用户:显示该订单详情；已取餐按钮高亮
用户->FrontEnd:点击已取餐按钮
FrontEnd->BackEnd:传递订单id，请求修改订单状态为已取餐
BackEnd->数据库:使用订单id修改具体表项
数据库 -> BackEnd:返回修改结果
BackEnd->FrontEnd:返回修改结果
alt 订单状态修改为已取餐
    FrontEnd->用户:显示订单状态为已取餐，已送达按钮高亮
    用户->FrontEnd:点击已送达按钮
    FrontEnd->BackEnd:传递订单id，请求修改订单状态为已送达
    BackEnd->数据库:使用订单id修改具体表项
    数据库 -> BackEnd:返回修改结果
    BackEnd->FrontEnd:返回修改结果
    alt 订单状态修改为已送达
        FrontEnd->BackEnd:传递用户id，查询该用户所有订单状态非已送达的订单
        BackEnd->数据库:使用用户id查询所有订单状态非已送达的订单
        数据库 -> BackEnd:返回查询结果
        BackEnd->FrontEnd:返回所有未完成订单列表
        FrontEnd->用户:更新未完成订单列表
end
end
deactivate FrontEnd
|||
@enduml