@startuml
'https://plantuml.com/sequence-diagram

autonumber
title 骑手注册

actor 用户
participant FrontEnd order 2
participant BackEnd order 3
activate BackEnd
participant queryWrapper order 4
database 数据库 order 6

activate 数据库
|||
用户 -> FrontEnd:登陆网站
activate FrontEnd

FrontEnd ->用户:显示登录界面
用户 -\ FrontEnd:点击注册界面，输入id
FrontEnd -> BackEnd: 请求校验id是否已存在
BackEnd -> queryWrapper:用id创建query实例
activate queryWrapper
BackEnd -> 数据库:使用query查询用户表是否存在该id
数据库 -> BackEnd:返回查询结果，id是否存在
deactivate queryWrapper
BackEnd->FrontEnd:返回查询结果，id是否存在
alt id不存在
    FrontEnd ->用户:id检查成功
    用户->FrontEnd:剩余注册所需信息
    FrontEnd->BackEnd:请求用户注册(所有注册所需信息)
    participant user order 5
    BackEnd->user:使用用户信息创建对象
    activate user
    BackEnd->数据库:使用mapper将user插入表
    数据库->BackEnd:返回插入结果
    deactivate user
    BackEnd->FrontEnd:返回注册结果

    alt 注册成功
        FrontEnd->用户:显示注册成功
    else 注册失败
        FrontEnd->用户:显示注册失败
    end
else id已存在
    FrontEnd ->用户:显示id已存在
end
|||
|||
|||

deactivate FrontEnd
@enduml