@startuml
'https://plantuml.com/activity-diagram-beta

'start
':ClickServlet.handleRequest();
':new page;
'if (Page.onSecurityCheck) then (true)
'  :Page.onInit();
'  if (isForward?) then (no)
'    :Process controls;
'    if (continue processing?) then (no)
'      stop
'    endif
'
'    if (isPost?) then (yes)
'      :Page.onPost();
'    else (no)
'      :Page.onGet();
'    endif
'    :Page.onRender();
'  endif
'else (false)
'endif
'
'if (do redirect?) then (yes)
'  :redirect process;
'else
'  if (do forward?) then (yes)
'    :Forward request;
'  else (no)
'    :Render page template;
'  endif
'endif
'
'stop
start
:进入商家首页;
:点击申请新店铺;
:填写新店铺信息;
:提交申请;
if (等待管理员审核) then (通过)
    :新建店铺成功;
else (不通过)
    :新建店铺失败;
endif
stop
@enduml
