@startuml
'https://plantuml.com/use-case-diagram
top to bottom direction



用户 -up- (3.修改个人信息)
用户 -up- (2.登录)
用户 -up- (1.注册)

骑手 -- (11.查询已完成送单记录)
骑手 -- (10.确认送达)
骑手 -- (9.查看未完成送货订单)

骑手 -up-|> 用户


:商家: as business
business -left-|> 用户

(3.申请新店铺) as (申请新店铺)
(6.管理店铺食品) as (管理店铺食品)
(7.处理用户订单) as (接单)
(8.查看店铺营业情况) as (查看店铺营业情况)
(4.选择店铺) as (选择店铺)
(5.管理店铺信息) as (管理店铺信息)

business -right- (选择店铺)
business -up- (申请新店铺)
business -- (管理店铺信息)
business -down- (管理店铺食品)
business -up- (接单)
business -down- (查看店铺营业情况)

客户 -up-|>用户
客户 -left-(16.查看订单)
客户 -up-(17.线上点餐)
客户 --(18.地址管理)

外卖平台管理员 -up- (12.查询订单)
外卖平台管理员 -down- (13.分配订单)
外卖平台管理员 -down- (14.查看店铺申请)
外卖平台管理员 -up- (15.将店铺上架展示界面)

@enduml