@startuml
'https://plantuml.com/activity-diagram-beta

|商家用户|
start
:进入商家首页;
:点击申请新店铺;
:填写新店铺信息;
:提交申请;
:等待管理员审核;
|管理员|
:商家用户提交的申请加入未审核店铺申请队列;
  :管理员检查该店铺申请;
  if(通过管理员审核) then(true)
    :修改审核状态为已通过;
    :将该店铺放上系统展示部分;
  else(false)
    :修改审核状态为未通过;
    :填写店铺申请的未通过理由;
  endif
  :发送审核结果给商家用户;

|商家用户|
if (查看管理员审核) then (通过)
    :新建店铺成功;
else (不通过)
    :新建店铺失败;
endif

stop

@enduml
