@startuml
'https://plantuml.com/activity-diagram-beta

start
:进入总订单界面;
:显示未完成送单和已完成送单;
split
:进入未完成送单界面;
:显示所有未完成的送货单;
:进入某一条送单详情;
:显示订单所有信息;
split
:进入送餐业务流程;
if (是否已取餐) then (true)

else (false)
:骑手到商户取餐;
:已取餐按钮高亮;
:点击取餐;
endif
:骑手到客户地址送餐;
:已送达按钮高亮;
:点击已送达;
:修改订单状态为已送达;
:将其从未完成送单中删除;
:加入已完成送单;

split again
end split
split again
:进入已完成送单界面;
:显示所有已完成的送货单;
split
:进入某一条送单详情;
:显示订单所有信息;
split again
end split
end split
stop
@enduml
