@startuml
'https://plantuml.com/use-case-diagram
left to right direction


rectangle 骑手子模块{
usecase 4.查看未完成送货订单
usecase 5.查询已完成送单记录

(4.查看未完成送货订单) ..> (4.1查看订单详情):include
(4.查看未完成送货订单) ..> (4.2查看商家地址):include
(4.查看未完成送货订单) ..> (4.3查看客户地址):include
(4.3查看客户地址) ..> (4.3.1确认送达):include
(4.2查看商家地址)..>(4.2.1确认取餐):include
(5.查询已完成送单记录)..> (4.1查看订单详情):include
}
骑手 -- (4.查看未完成送货订单)
骑手 -- (5.查询已完成送单记录)

用户 -- (1.登录)
用户 -- (3.注册)
用户 -- (2.修改个人信息)
骑手 --|> 用户
(2.修改个人信息)...>(2.1修改姓名):include
(2.修改个人信息)...>(2.2修改电话):include
(2.修改个人信息)...>(2.3修改头像):include
(2.修改个人信息)...>(2.4修改地址):include
@enduml