@startuml
'https://plantuml.com/class-diagram

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
left to right direction

'List <|-- AbstractList
'Collection <|-- AbstractCollection
class 订单状态{
    + 状态：int
}

class 送货订单{
+ 订单编号:string
+ 订单状态:int
+ 商家地址:string
+ 客户地址:string
+ 取餐时间:Date
+ 送达时间:Date
+ 订单创建时间:Date
}

'class 未完成订单 {
' 送货订单列表:送货订单[]
' 查看详细订单(订单编号:string):送货订单
' 确认取餐(订单编号:string):送货订单
' 确认送达(订单编号:string):送货订单
'}
'
'class 已完成订单 {
'  送货订单列表:送货订单[]
'   查看详细订单(订单编号:string):送货订单
'}

class 骑手个人信息{
+ 姓名:string
+ 电话:string
+ 地址:string
+  头像:string
}
rectangle 骑手{
}

骑手 "1" -- "1" 骑手个人信息
骑手 "1" -- "0..*" 送货订单
送货订单 "0..*" -- "1" 订单状态

note right of 订单状态 :"订单状态为0代表未取餐，1代表已取餐未送达，2代表送达"


@enduml