@startuml
'https://plantuml.com/class-diagram





rectangle 骑手子系统{
rectangle FrontEnd{
}
FrontEnd -->骑手Controller:通过http使用restfulAPI方式调用

rectangle BackEnd{
class 骑手Controller{
    + 骑手登录(rider:骑手用户):登录结果
    + 骑手注册(rider:骑手用户):注册结果
    + 骑手id检查(riderId:string):检查结果
    + 查询已完成订单(riderId:string):List<送货订单>
    + 查询未完成订单(riderId:ID):List<送货订单>
    + 订单取餐(订单ID:string):取餐结果
    + 订单送达(订单ID:string):送达结果
    }
骑手Controller o-- 骑手Service
骑手Controller --> 骑手Service:调用功能

    class 骑手mapper{
    }
    class 送货订单mapper{
    }

Interface 骑手Service{
    + 查询骑手已完成订单(riderId:ID):List<送货订单>
    + 查询骑手未完成订单(riderId:ID):List<送货订单>
    + 登录(user:User):登录结果
    + 注册(user:User):注册结果
    + 订单取餐(订单ID:string):取餐结果
    + 订单送达(订单ID:string):送达结果
}
class 骑手ServiceImpl{
    + 查询骑手已完成订单(riderId:ID):List<送货订单>
    + 查询骑手未完成订单(riderId:ID):List<送货订单>
    + 登录(user:User):登录结果
    + 注册(user:User):注册结果
    + 订单取餐(订单ID:string):取餐结果
    + 订单送达(订单ID:string):送达结果
}
骑手ServiceImpl o-- 骑手mapper
骑手ServiceImpl o-- 送货订单mapper
}
骑手ServiceImpl ..>骑手Service
rectangle PO{
    class 送货订单{
    + 订单编号:string
    + 订单状态:int
    + 商家地址:string
    + 客户地址:string
    + 取餐时间:Date
    + 送达时间:Date
    + 订单创建时间:Date
    }

    class 骑手用户{
    }

        class User{
        + ID:string
        + 姓名:string
        + 电话:string
        + 地址:string
        + 头像:string
        }
骑手用户-|>User:extends
}
}

@enduml