@startuml
'https://plantuml.com/state-diagram

scale 350 width


state 查询操作 {
  [*] -->读锁加锁
  读锁加锁 --> 查询
  查询 --> 读锁解锁
}

state 缓存{
查询-->检查缓存

检查缓存-->返回缓存信息: 存在缓存

检查缓存-->数据库查询: 不存在缓存
数据库查询-->添加缓存条目

state 删除缓存条目
state 更新缓存条目
}
state 信息修改操作 {
[*]-->写锁加锁
写锁加锁-->添加信息
写锁加锁-->删除信息
写锁加锁-->更新信息

添加信息-->添加数据库条目
添加数据库条目-->添加缓存条目

}
state 数据库{
state 数据库查询
}
@enduml